USE SSAFYDB;

#1
SELECT * FROM EMP WHERE YEAR(HIREDATE) = 2014;
#2
SELECT * FROM EMP WHERE ENAME LIKE '%S%';
#3
SELECT * FROM EMP WHERE COMM IS NULL;
#4
SELECT ENAME, DEPTNO, SAL, SAL*13.5 FROM EMP WHERE DEPTNO = 30;
#5
SELECT ENAME, SAL, SAL * 1.5 AS 경조사 FROM EMP WHERE SAL >= 2000;